// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vixugcvdljojguqkxevw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpeHVnY3ZkbGpvamd1cWt4ZXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDk2MzQsImV4cCI6MjA2OTEyNTYzNH0.RuqWfxIemtVrOJjgw-BuQNmPXRu-VAXx-xF5bvr198U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});